dataset:
  root: "data"
  batch_size: 32
  num_workers: 8
  download: true
model:
  name: "pointnet2"
  in_channels: 9
  num_classes: 41
optimizer:
  name: "adam"
  lr: 0.001
  momentum: 0.9
trainer:
  device: "cuda"
  epochs: 100
  logdir: "logs/scenenn/pointnet2"
  log_interval: 5
  eval_freq: 10
  monitor: "max accuracy"
  tensorboard: false
  early_stopping: false
  resume: false
